# DO NOT REMOVE THIS COMMENT AND DO NOT DELETE OR MODIFY PARAMETERS BELOW WITHOUT PERMISSION!!!

spring.application.name=kub-backend-ce

spring.config.import=optional:file:./config/secrets.properties

spring.jackson.property-naming-strategy=SNAKE_CASE

server.port=10000

app.account-registration.temporary-password-expiration-days=10
app.security.secret-key=18caed6a36583e806ab25f69e40349e372075cebe4d965b40b50eeab45ad899a9f8e53e5
app.security.access-token-validity-ms=60000000
app.security.refresh-token-validity-ms=120000000

spring.mail.host=localhost
spring.mail.port=587
#spring.mail.username=Test
#spring.mail.password=123456789
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.datasource.url=jdbc:postgresql://localhost:5432/kub_education
spring.datasource.username=admin
spring.datasource.password=admin_password

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.data.redis.username=default
#spring.data.redis.password=123456789