# DO NOT REMOVE THIS COMMENT AND DO NOT DELETE OR MODIFY PARAMETERS BELOW WITHOUT PERMISSION!!!

spring.application.name=kub-super-admin-backend

spring.config.import=classpath:/secrets.properties

spring.jackson.property-naming-strategy=SNAKE_CASE

server.port=${server.port}

app.account-registration.temporary-password-expiration-days=${account-registration.temporary-password-expiration-days}

app.security.super-admin-header-secret=${security.super-admin-header-secret}

spring.mail.host=${smtp.host}
spring.mail.port=${smtp.port}
spring.mail.username=${smtp.username}
spring.mail.password=${smtp.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=${datasource.url}
spring.datasource.username=${datasource.username}
spring.datasource.password=${datasource.password}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.flyway.enabled=true
spring.flyway.url=${datasource.url}
spring.flyway.user=${datasource.username}
spring.flyway.password=${datasource.password}
spring.flyway.default-schema=public

spring.data.redis.host=${data.redis.host}
spring.data.redis.port=${data.redis.port}
spring.data.redis.username=${data.redis.username}
spring.data.redis.password=${data.redis.password}