# DO NOT REMOVE THIS COMMENT AND DO NOT DELETE OR MODIFY PARAMETERS BELOW WITHOUT PERMISSION!!!

spring.application.name=kub-super-admin-backend

spring.config.import=classpath:/secrets.properties

spring.jackson.property-naming-strategy=SNAKE_CASE

super.admin.key=${super.admin.key}

server.port=${server.port}

jwt.secret=${jwt.secret}
jwt.accessTokenExpiration=${jwt.accessTokenExpiration}
jwt.refreshTokenExpiration=${jwt.refreshTokenExpiration}

spring.mail.host=${smtp.host}
spring.mail.port=${smtp.port}
spring.mail.username=${smtp.username}
spring.mail.password=${smtp.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=${datasource.url}
spring.datasource.username=${datasource.username}
spring.datasource.password=${datasource.password}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.flyway.enabled=true
spring.flyway.url=${datasource.url}
spring.flyway.user=${datasource.username}
spring.flyway.password=${datasource.password}
spring.flyway.default-schema=public